language: javascript

branches:
  only:
    - master

before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sleep 3

script:
  - yarn install
  - yarn run test


notifications:
  webhooks: https://coveralls.io/webhook?repo_token=ZCbNMWafZoA7syUoOJsSvmcbLKwGtlGnI
